services:
  - type: web
    name: laravel-render
    env: nixpacks
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install && npm run build
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
